import streamlit as st
import matplotlib.pyplot as plt
import PyPDF2
import io
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
import datetime

# ---------------- CONFIG ----------------
st.set_page_config(page_title="Professional ATS System", layout="centered")
TEAL = "#117A65"

# ---------------- FUNCTIONS ----------------

def extract_text(pdf_file):
    """Extracts text from a PDF file."""
    reader = PyPDF2.PdfReader(pdf_file)
    text = ""
    for page in reader.pages:
        text += page.extract_text()
    return text.lower()

def generate_scores():
    """Dummy function to simulate score computation."""
    return {
        "Technical Skills": 40,
        "Experience Match": 14.87,
        "Soft Skills": 66.67,
        "Resume Quality": 60,
        "Searchability": 100,
        "Metrics Usage": 100
    }

def improvement_suggestions():
    return [
        "Add missing technical skills explicitly mentioned in the job description.",
        "Align your experience section more closely with job description keywords.",
        "Mention measurable achievements using numbers and metrics.",
        "Add advanced tools such as SQL, Tableau, or Power BI if applicable.",
        "Use strong action verbs and concise bullet points."
    ]

def resume_strengths():
    return [
        "Clear resume structure and readable formatting",
        "Relevant job role alignment",
        "Good use of soft skills keywords",
        "ATS-friendly layout without images or tables"
    ]

def section_feedback():
    return {
        "Experience": "Relevant role mentioned, but lacks quantified results.",
        "Skills": "Core skills listed clearly; advanced tools can be added.",
        "Soft Skills": "Good coverage of teamwork and communication.",
        "Formatting": "Clean and ATS-friendly with good spacing."
    }

def create_pdf_report(resumes_data):
    """Generates a professional PDF report for multiple resumes."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("<b>ATS Resume Evaluation Report</b>", styles["Title"]))
    elements.append(Spacer(1, 10))
    elements.append(Paragraph(f"Generated on: {datetime.datetime.now().strftime('%d %b %Y')}", styles["Normal"]))
    elements.append(Spacer(1, 10))

    for data in resumes_data:
        elements.append(Paragraph(f"<b>Candidate Resume:</b> {data['name']}", styles["Heading2"]))
        elements.append(Paragraph(f"Target Role: {data['role']}", styles["Normal"]))
        elements.append(Paragraph(f"Overall ATS Score: <b>{data['overall_score']}%</b>", styles["Normal"]))
        elements.append(Spacer(1, 5))

        # Score table
        table_data = [["Category", "Score (%)"]] + [[k, v] for k, v in data['scores'].items()]
        table = Table(table_data)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.HexColor(TEAL)),
            ("TEXTCOLOR", (0,0), (-1,0), colors.white),
            ("GRID", (0,0), (-1,-1), 1, colors.black),
        ]))
        elements.append(table)
        elements.append(Spacer(1, 5))

        # Suggestions
        elements.append(Paragraph("<b>Improvement Recommendations:</b>", styles["Heading3"]))
        for tip in data['improvements']:
            elements.append(Paragraph(f"- {tip}", styles["Normal"]))

        # Strengths
        elements.append(Paragraph("<b>Resume Strengths:</b>", styles["Heading3"]))
        for s in data['strengths']:
            elements.append(Paragraph(f"- {s}", styles["Normal"]))

        elements.append(Spacer(1, 20))

    # Footer
    elements.append(Paragraph(
        "<i>Generated by Professional ATS Resume Scoring System</i>", styles["Normal"]
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer

# ---------------- UI ----------------
st.title("📄 Professional ATS Resume Scoring System")

job_role = st.selectbox("Select Job Role", ["", "Data Analyst", "Data Scientist", "Web Developer"])
jd = st.text_area("Paste Job Description (Optional)")

uploaded_files = st.file_uploader("Upload Resume PDFs", type=["pdf"], accept_multiple_files=True)

# ---------------- ANALYSIS ----------------
if st.button("Run ATS Analysis"):
    if not uploaded_files:
        st.error("❌ Please upload at least one PDF file.")
    elif not job_role:
        st.error("❌ Please select a job role.")
    else:
        resumes_data = []
        for file in uploaded_files:
            resume_text = extract_text(file)
            scores = generate_scores()  # Replace with real computation
            overall_score = round(sum(scores.values()) / len(scores), 2)

            resumes_data.append({
                "name": file.name,
                "role": job_role,
                "scores": scores,
                "overall_score": overall_score,
                "improvements": improvement_suggestions(),
                "strengths": resume_strengths(),
                "sections": section_feedback()
            })

        # Sort resumes by score (descending)
        resumes_data = sorted(resumes_data, key=lambda x: x['overall_score'], reverse=True)

        st.subheader("🏆 Resume Ranking")
        for idx, r in enumerate(resumes_data, 1):
            st.write(f"{idx}. {r['name']} — {r['overall_score']}% ATS Match")

            # Show chart
            fig, ax = plt.subplots(figsize=(4, 2.5))
            ax.barh(list(r['scores'].keys()), list(r['scores'].values()), color=TEAL)
            ax.set_xlim(0, 100)
            ax.set_title("ATS Score Breakdown", fontsize=9)
            ax.tick_params(labelsize=7)
            st.pyplot(fig)

            # Skill Gap / Improvements
            st.info("Missing Skills: SQL, Excel, Tableau, Power BI")
            st.warning("Top Recommendations:")
            for tip in r['improvements']:
                st.write(f"- {tip}")

        # PDF Download
        pdf = create_pdf_report(resumes_data)
        st.download_button(
            label="📥 Download Professional PDF Report",
            data=pdf,
            file_name="ATS_Professional_Report.pdf",
            mime="application/pdf"
        )

st.caption("© Professional ATS System | AI-powered Resume Evaluation")



